import { View, Text, Button,FlatList } from 'react-native'
import React,{useState} from 'react'

export default function Colorapp() {
   const [colors,setColor]=useState([])
 
  return (
    <View>
      {/* here when the button is pressed the array of colors is not modified instead a new array is prepared
      which contains the items of all the previous array and a new color(item) generated by randomrgb() function */}
      {/* now when we press the button the whole return statement will rerender and new view is displayed on screen
      and a new array with preexsiting value from previous values of colors and one new value of colors generated 
      by randonrgb function will be created */}
      <Button title='Generate random Color' onPress={()=>setColor([...colors,randomrgb()])}/>
      {/* <View style={{height:100,width:100,backgroundColor:randomrgb()}}/> */}
      

      {/* here flatlist is used to display on screen the list of colors in the colors array
      when using this flatlist just comment the upper view<View style={{height:100,width:100,backgroundColor:randomrgb()}}/> */}
      <FlatList
      keyExtractor={(item)=>item}
      data={colors}
      renderItem={({item})=>
 
      <View style={{height:100,width:100,backgroundColor:item}}/>
    
    }
      />
    </View>
  )
}
const randomrgb=()=>{
    const red=Math.floor(Math.random()*256)
    const green=Math.floor(Math.random()*256)
    const blue=Math.floor(Math.random()*256)
    return `rgb(${red},${green},${blue})`
}